### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@jourdain Can you take a look when you get a chance?  I'm just waiting to get the new pvw version (I'll merge that PR now) before rebuilding the dist, and then I'll push one more commit on this PR.

**Comment by jourdain** [comment]
LGTM

**Comment by jourdain** [comment]
BTW, you need to update the dist of visualizer

**Comment by scottwittenburg** [comment]
Well I did mention that in my initial comment ;-)

**Pull request merged**
