### PR TITLE
fix(proxies): React to view id change, if applicable

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@jourdain This allows us to validate the path where we change the viewId prop on the pvw geometry renderer, and it seems to work.

**Comment by jourdain** [comment]
I'm guessing without it you couldn't load the state file properly but with it everything works as expected?

**Comment by jourdain** [comment]
If so, then just merge it.

**Comment by jourdain** [comment]
BTW, Outline representation is not working with local rendering.

**Comment by scottwittenburg** [comment]
Yes, with this change (as well as the PV one) everything seemed to work as expected.  I haven't looked into the outline issue yet, but thought that was not expected to work yet.

**Comment by scottwittenburg** [comment]
Hmmm, just tested outline representation in local rendering mode on my linux machine, and it seems to work.

**Pull request merged**
