### PR TITLE
fix(docs): Fix incorrect docs

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@jourdain I think this could be ready.  I'll do a release build and push the dist file once you think the content is right.

**Comment by jourdain** [comment]
Push the dist, the readme does not impact it

**Comment by jourdain** [comment]
I was ready to merge.

**Comment by jourdain** [comment]
can I?

**Comment by scottwittenburg** [comment]
You can, unless you want to wait for the checks to complete.

**Pull request merged**
